# Generated by Django 4.0.1 on 2022-01-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('useragent', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
