# Generated by Django 4.0.1 on 2022-01-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_delegate', '0002_clientdata_created_at_clientdata_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientData',
            new_name='Job',
        ),
    ]
