# Generated by Django 4.0.1 on 2022-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_delegate', '0004_job_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaveServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
