#!/bin/bash

echo "!!!Creating database!!!"
echo "Checking requirements..."

pkg=postgresql

status="$(dpkg-query -W --showformat='${db:Status-Status}' "$pkg" 2>&1)"

if [ "$status" = installed ]; then
	echo "PostgreSQl installed"
else
	echo "PostgreSQL didn't installed"
	sudo apt install $pkg
fi

set -e
echo "Enter database name:"
read DB_NAME
echo "Enter database - $DB_NAME user name:"
read DB_USER
echo "Enter user - $DB_USER password:"
read DB_USER_PASS
#DB_NAME=${1:-my_pg_user}
#DB_USER=${2:-my_awesome_db}
#DB_USER_PASS=${3:-hard_password}
sudo su postgres <<EOF
createdb  $DB_NAME;
psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_USER_PASS';"
psql -c "grant all privileges on database $DB_NAME to $DB_USER;"
echo "Postgres User '$DB_USER' and database '$DB_NAME' created."
EOF
